# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'sample-users' do
    pod 'SVProgressHUD'
    pod 'NMPaginator'
end

target 'sample-usersTests' do

end

