# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'sample-videochat-webrtc' do
    pod 'SVProgressHUD'
end

target 'sample-videochat-webrtcTests' do

end

