# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

inhibit_all_warnings!
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'sample-videochat-webrtc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'QuickBlox', '~> 2.18.1'
  pod 'Quickblox-WebRTC', '~> 2.8.1'
  
end
