platform :ios, "7.0"

pod 'SVProgressHUD', '~> 1.1.3'

#Using bolts 1.5.0+ due to Xcode 6 support (no generics and nullability)
pod 'Bolts', '~> 1.5.0'

#Production pod
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '6d70c0f04ef2c199b928ff1a2f8edf9d48b510c5'

#For development pods
#pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'

#Production pod
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => 'aae171d8ef0121342f3bf815757452e7a259735c'

#For development pods
#pod 'QMServicesDevelopment', :path => '../../q-municate-services-ios/'

pod 'MPGNotification', '~> 1.2'