platform :ios, "8.0"

target 'samplechat' do

pod 'SVProgressHUD', '~> 1.1.3'

#Using bolts 1.5.0+ due to Xcode 6 support (no generics and nullability)
pod 'Bolts', '~> 1.5.0'

#Production pod
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => 'fe9bd013a90ab54c1b415b104628c338d71d4f5b'

#For development pods
#pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'

#Production pod
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => '8fa3545c34683bc1f547041300a00e91efc4c6c0'

#For development pods
#pod 'QMServicesDevelopment', :path => '../../q-municate-services-ios/'

pod 'SearchEmojiOnString'

pod 'UIAlertView+Blocks'

pod 'Fabric'

pod 'Crashlytics'

end
