platform :ios, "7.0"

pod 'SVProgressHUD'
pod 'TWMessageBarManager', '~> 1.7.2'

#Production pod
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '17ada21717a26235a73069a7ef0e396871ac8514'

#For development pods
#pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'

#Production pod
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => 'e24221300d4c40fab4404b2cd91d0d2a9f957afc'

#For development pods
#pod 'QMServicesDevelopment', :path => '../../q-municate-services-ios/'