# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'sample-conference-videochat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'QuickBlox', '~> 2.17.10'
  pod 'Quickblox-WebRTC', '~> 2.7.6'

end
