# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
inhibit_all_warnings!

target 'sample-push-notifications-swift' do

    pod 'QuickBlox', '~> 2.17.7'
    pod 'SVProgressHUD'

end
