platform :ios, "7.0"

pod 'SVProgressHUD', '~> 1.1.3'
pod 'TWMessageBarManager', '~> 1.7.2'

#Production pod
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '188fb5807bc3650b93b4b35de4b08799f12c4a2e'

#For development pods
#pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'

#Production pod
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => 'e00e4305f4005b89ea9a235e8fcb28ea99454177'

#For development pods
#pod 'QMServicesDevelopment', :path => '../../q-municate-services-ios/'