
platform :ios, "9.0"

use_frameworks!

target 'sample-chat-swift' do
    
    #    pod 'QMServicesDevelopment', :path => '../../q-municate-services-ios/'
    #    pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'
    
    pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :tag => '0.6'
    pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :tag => '0.6.1'
    pod 'SVProgressHUD', '~> 1.1.3'
    pod 'SearchEmojiOnString'
    pod 'Fabric'
    pod 'Crashlytics'
end
