# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'sample-videochat-webrtc-swift' do
  inhibit_all_warnings!
  
  pod 'QuickBlox', '~> 2.17.10'
  pod 'Quickblox-WebRTC', '~> 2.7.6'
  pod 'SVProgressHUD', '~> 2.2.5'

end
