# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'sample-videochat-webrtc-swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'QuickBlox', '~> 2.17.1'
  pod 'Quickblox-WebRTC', '~> 2.7.2'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'Fabric'
  pod 'Crashlytics'

end
