# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
install! 'cocoapods', :warn_for_unused_master_specs_repo => false
target 'sample-videochat-webrtc-swift' do
  inhibit_all_warnings!
  
  pod 'QuickBlox'
  pod 'Quickblox-WebRTC', '2.7.6'

end
