# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-QMChatViewController' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'QMChatViewController'
    pod 'QuickBlox', '~> 2.17'
    pod 'Quickblox-WebRTC', '~> 2.7'
    pod 'SDWebImage/WebP'
    pod 'SDWebImage/GIF'

end
