# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'sample-push-notifications' do
    pod 'SVProgressHUD'
end

target 'sample-push-notificationsTests' do

end

