platform :ios, "10.2"

use_frameworks!

target 'samplechat' do
    inhibit_all_warnings!
    
    pod 'QuickBlox', '~> 2.17.1'
#   Additional libraries:
    pod 'SDWebImage', '~> 4.3.3'
    pod 'TTTAttributedLabel', '~> 2.0.0'
    pod 'SVProgressHUD', '~> 1.1.3'
    
end
