platform :ios, "13.0"

use_frameworks!

target 'samplechat' do
    inhibit_all_warnings!
    pod 'QuickBlox', '~> 2.17.7'
    # Additional libraries:
    pod 'SDWebImage', '~> 4.4.7'
    pod 'TTTAttributedLabel', '~> 2.0.0'
    pod 'SVProgressHUD'
    
end
