platform :ios, '10.0'

target 'sample-conference-videochat-swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'QuickBlox', '~> 2.15'
  pod 'Quickblox-WebRTC', '~> 2.7.3'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'Fabric'
  pod 'Crashlytics'

end
