platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

target 'sample-conference-videochat-swift' do

  pod 'QuickBlox', '~> 2.17.7'
  pod 'Quickblox-WebRTC', '~> 2.7.4'
  pod 'SVProgressHUD'
  pod 'SDWebImage', '~> 4.4.7'
  
  pod 'TTTAttributedLabel', '~> 2.0.0'
  
end
