platform :ios, '13.0'

inhibit_all_warnings!

target 'sample-conference-videochat-swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'QuickBlox', '~> 2.17.7'
  pod 'Quickblox-WebRTC', '~> 2.7.4'
  pod 'SVProgressHUD'
  pod 'SDWebImage', '~> 4.4.7'
  pod 'TTTAttributedLabel', '~> 2.0.0'
  
end
